### ISSUE TITLE
Can't invoke functions on 0.6.6-alpha.0

### ISSUE THREAD

**Issue by 0xHyoga** [Shard-Labs/starknet-hardhat-plugin#213]
Everytime i try to invoke a function i get the following error:

```
Entry point 0x162da33a4585851fe8d3af3c2a9c60b557814e221e0d4f30ff0b2189d9c7775 not found in contract 
with class hash 0x148abd2788c5606368d2ad824da288b46e69db0c628f969b1c271a99adc3553.
```

**Comment by 0xHyoga** [comment]
Calling seems to work fine however

**Comment by FabijanC** [comment]
I will assume you are using plugin version 0.6.6-alpha.0

Since Starknet 0.10.0, transactions with version=1 (now the preferred and default value), can only be sent through an account (i.e. through the `__execute__` function). Calls shouldn't be done through an account, but directly on contracts. Read [here](https://github.com/Shard-Labs/starknet-hardhat-plugin/tree/v0.6.6-alpha.0#accounts) more about interaction through accounts.

Invoking through account has been present for some time now, but its necessity wasn't properly documented with the last version, so I updated [these release notes](https://github.com/Shard-Labs/starknet-hardhat-plugin/releases/tag/v0.6.6-alpha.0) (only the change in calling was properly documented).

In the next version (which will happen very soon), I will also try to update the examples shown in the docs and [the example repository](https://github.com/Shard-Labs/starknet-hardhat-example).
