### ISSUE TITLE
Invoke fails on ^0.6.6-alpha.2

### ISSUE THREAD

**Issue by hsouf** [Shard-Labs/starknet-hardhat-plugin#214]
```
await l2deployer.invoke(l2Bridge, "set_l1_bridge",
        {
          l1_bridge_address: BigInt(l1Bridge.address),
        },
      );
```

after upgrading to all invoke transactions started to fail
`Invoke transaction 0x422ab9e36b8702aafa214e031c869e590d89bb3939a6a866fc050e81b368285 is REJECTED. DEBUG TODO`

**Comment by hsouf** [comment]
Error: Transaction rejected. Error message:

Error at pc=0:68:
Signature (1926467653218350765052855379800169928694867929804139547763957020183958744588, 124100029744818950652213442615959123540331955983366944949853234847516712144), is invalid, with respect to the public key 3021906858350333702822191182504712146320192971125811856520352776643124090741, and the message hash 25778650572456588604629633929640182703692183083285162245104816656299650438.
Cairo traceback (most recent call last):
Unknown location (pc=0:500)
Unknown location (pc=0:464)
Unknown location (pc=0:169)

**Comment by FabijanC** [comment]
And it worked with 0.6.6-alpha.1? In Starknet v0.10 with tx version = 1, all invokes have to be done through accounts.

I apologize for the `DEBUG TODO`, I was publishing everything locally and I forgot to recompile after removing those two words (that's why they aren't in the source code, but that should be the only difference between the source and the compiled code).

**Comment by FabijanC** [comment]
So, instead of doing `contract.invoke("foo", ...)` you need to do `account.invoke(contract, "foo", ...)`.
But the signature error looks like it's coming from an account invocation or some place similar, it couldn't have come from regular `contract.invoke(...)`

p.s. I had a typo in the previous message (I mentioned 0.6.6-alpha.1, now it's corrected to say 0.6.6-alpha.0)

**Comment by hsouf** [comment]
Yes, actually all invokes are done through accounts, but some invokes started to fail weirdly after upgrading to 0.6.6-alpha.2

**Comment by hsouf** [comment]
@FabijanC find [here](https://github.com/aave-starknet-project/aave-starknet-bridge/blob/cairo-0.10.0/scripts/deploy.ts) the link to my deployment script. Could be helpful for debugging. Thanks for your swift reply btw!

**Comment by FabijanC** [comment]
Sorry, somehow I misread your first code excerpt, indeed you are invoking through an account.

So, the implementation and signing of the account has changed. Since plugin v0.6.6-alpha.2 the plugin uses the updated OpenZeppelin implementation, adapted to work with Starknet 0.10. Which version of Devnet are you using? Since v0.2.0, Devnet is adapted to work with Starknet 0.10, and since v0.3.1, it also predeploys the same mentioned OpenZeppelin accounts: https://github.com/Shard-Labs/starknet-devnet#predeployed-accounts

**Comment by hsouf** [comment]
I'm using straknet-devnet 0.3.1,  maybe it's a problem with the OpenZeppelin 0.4.0b-fork

**Comment by hsouf** [comment]
Also @FabijanC I get `Invoke Transaction ....... IS REJECTED`  even if successful!

**Comment by FabijanC** [comment]
I've sent you an invite to discuss this on Google Meet, I used the email address provided on https://github.com/hsouf

**Comment by FabijanC** [comment]
Turns out that the rejected transaction is the expected behavior in this case; it was happening in a test which was expecting an invoke transaction to fail. A message informing of transaction was being printed, making it look like unwanted behavior.
