### ISSUE TITLE
Upgrade internal presets from OpenZeppelin

### ISSUE THREAD

**Issue by JamesEarle** [Shard-Labs/starknet-hardhat-plugin#219]
I'm trying to compile an ERC721 sample contract for StarkNet. The problem is that it's not able to compile the reference preset given by OpenZeppelin because internally it does not have the latest (`0.10.0`) contracts that include modified syntax.

I'm using version `0.6.6` of the hardhat plugin.

I can see by checking `config.json` internally it is using `"CAIRO_LANG": "0.10.0"` and `"STARKNET_DEVNET": "0.3.1"`

I have `python --version` as `Python 3.8.10`

I have `openzeppelin-cairo-contracts 0.4.0b0` when I run `pip list`

Compiling through the CLI with regular the regular `starknet-compile` command works and generates the expected output and abi json files.

I've created a command in my `package.json` for compiling starknet contracts with this plugin `stark:compile: "hardhat starknet-compile`

Calling `sudo yarn stark:compile stark_contracts/ERC721.cairo` fails because it is using the dockerized environment that has not updated the openzeppelin contracts.

![image](https://user-images.githubusercontent.com/5976499/191867947-20914a71-15bf-49e0-82b7-b1767cffec04.png)

**Comment by FabijanC** [comment]
Thank you for reporting, as you can see on [Docker Hub](https://hub.docker.com/repository/docker/shardlabs/cairo-cli), the following docker images have been updated:
- `shardlabs/cairo-cli:0.10.0`
- `shardlabs/cairo-cli:0.10.0-arm`
- `shardlabs/cairo-cli:latest`
- `shardlabs/cairo-cli:latest-arm`

You need to manually update the image:
`docker pull shardlabs/cairo-cli:0.10.0`

Alternatively, you can set your hardhat config file to use your local cairo-lang installation instead of the dockerized version:
https://github.com/Shard-Labs/starknet-hardhat-plugin#existing-virtual-environment

**Comment by JamesEarle** [comment]
This issue has been addressed by the team with a response in the [Discord here](https://discord.com/channels/793094838509764618/912735106899275856/1022790076914221066)

![image](https://user-images.githubusercontent.com/5976499/192010498-150a7978-abae-4336-b313-59662282ead7.png)
