### ISSUE TITLE
Replace bash tests with JS

### ISSUE THREAD

**Issue by FabijanC** [Shard-Labs/starknet-hardhat-plugin#248]
Instead of calling direct commands in bash (e.g. `npx hardhat starknet-compile`), we should use a JS library which wraps this. Not talking about child_process functionality, rather something more adapted for testing CLI tools.

**Comment by Nathan-SL** [comment]
* Jest doesn't seem to test it's CLI commands
* The third-party [plugins](https://hardhat.org/hardhat-runner/plugins) (haven't checked all of 'em) either don't have what we want or they perform testing the way hardhat-core tests its CLI command (which don't have a way to read it's `stdout` like below)

```ts
await this.env.run("starknet-deploy", {
                paths: ["starknet-artifacts/contracts/contract.cairo"],
                inputs: "13",
                starknetNetwork: "devnet"
});
``` 
 * With Shelljs it'd be a better and faster way to replace the bash to TS because we wouldn't do any of the hardhat environment handlings (because we would only change `check.sh` to presumably `check.ts`). Also, having a function that accepts the hardhat commands and returns a stdout would be easier. 
* Regarding commander, I see it may force us to first create a command and then do the testing which would require a big change.
